name: Run Notebook

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert nbformat
      - name: Execute notebook
        run: jupyter nbconvert --execute --to notebook notebooks/task3_sentiment_analysis/sentiment_analysis.ipynb